import type { Metadata } from 'next';
import './globals.css';
import Container from '@/components/Container';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: {
    default: 'Blog App - Este é um blog com next.js',
    template: '%s | The Blog',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Container>
          <Header />
          {children}

          <footer>
            <p className='text-6xl font-bold text-center py-8'>
              Aqui é a footer
            </p>
          </footer>
        </Container>
      </body>
    </html>
  );
}
